name: 'Runtime analysis'

on:
  workflow_dispatch:
  push:
    branches:
      - build
  pull_request:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release, MinSizeRel]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: raspios_lite_arm64:latest
        cpu: max:cortex-a72
        cpu_info: cpuinfo/raspberrypi_4b
        copy_artifact_path: build/ycc2rgb_${{ matrix.build-type }};build/*.s
        copy_artifact_dest: build/
        commands: |
            cd build
            apt install -y cmake
            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
            make
            mv ycc2rgb ycc2rgb_${{ matrix.build-type }}
            mv ycc2rgb.s ycc2rgb_${{ matrix.build-type }}.s
            mv conversion.s conversion_${{ matrix.build-type }}.s
            mv util.s util_${{ matrix.build-type }}.s
    - uses: actions/upload-artifact@v3
      with:
        name: ycc2rgb_${{ matrix.build-type }}
        path: build/
        if-no-files-found: error


  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download builds
      uses: actions/download-artifact@v3
      with:
        path: build
    - name: Zip release
      run: |
        zip -r release.zip build app include lib testimages
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
