name: 'Runtime analysis'

on:
  workflow_dispatch:
  push:
    branches:
      - build
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: raspios_lite_arm64:latest
        cpu: max:cortex-a72
        cpu_info: cpuinfo/raspberrypi_4b
        commands: |
            apt install -y cmake
            cmake .
            make
            zip release.zip app include lib testimages ycc2rgb

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        tag: v$(date +%Y%m%d.%H%M%S)
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
